### ISSUE TITLE
Quantidade de Libs desnecessárias

### ISSUE THREAD

**Issue by carlinhoshk** [pycodebr/apuracao_eleicoes_2022#1]
![image](https://user-images.githubusercontent.com/40872405/193477053-5b1d3f66-a021-4248-8a3c-bd5ef6059d0a.png)

![image](https://user-images.githubusercontent.com/40872405/193477063-ef1c4a2b-e5ef-44f0-bd6f-a33e27907366.png)

o arquivo Main só usa 3 libs porque o requirements tem tantas libs desnecessárias ?

**Comment by meu-bem** [comment]
Esse arquivo `requirements.txt` é gerado automaticamente pelo `pip`. Algumas libs ten como dependência outras libs, como é o caso do `pandas`que tem como dependência o `numpy`, por isso o número grande de libs.
